// Generated by scripts/build-regions.mjs — do not edit manually.
// Village data is shipped as static JSON under /data/regions/villages and fetched at
// runtime, so the ~17.76 MB of village data is never parsed/transformed by the build.
// Valid state codes: 35, 28, 12, 18, 10, 4, 22, 7, 30, 24, 6, 2, 1, 20, 29, 32, 37, 31, 23, 27, 14, 17, 15, 13, 21, 34, 3, 8, 11, 33, 36, 38, 16, 9, 5, 19.

import type { RegionPlace } from '../../../types';

const VILLAGE_DATA_BASE = `${import.meta.env.BASE_URL}data/regions/villages`;

const VILLAGE_DATA_URL: Record<number, string> = {
  35: `${VILLAGE_DATA_BASE}/35.json`,
  28: `${VILLAGE_DATA_BASE}/28.json`,
  12: `${VILLAGE_DATA_BASE}/12.json`,
  18: `${VILLAGE_DATA_BASE}/18.json`,
  10: `${VILLAGE_DATA_BASE}/10.json`,
  4: `${VILLAGE_DATA_BASE}/4.json`,
  22: `${VILLAGE_DATA_BASE}/22.json`,
  7: `${VILLAGE_DATA_BASE}/7.json`,
  30: `${VILLAGE_DATA_BASE}/30.json`,
  24: `${VILLAGE_DATA_BASE}/24.json`,
  6: `${VILLAGE_DATA_BASE}/6.json`,
  2: `${VILLAGE_DATA_BASE}/2.json`,
  1: `${VILLAGE_DATA_BASE}/1.json`,
  20: `${VILLAGE_DATA_BASE}/20.json`,
  29: `${VILLAGE_DATA_BASE}/29.json`,
  32: `${VILLAGE_DATA_BASE}/32.json`,
  37: `${VILLAGE_DATA_BASE}/37.json`,
  31: `${VILLAGE_DATA_BASE}/31.json`,
  23: `${VILLAGE_DATA_BASE}/23.json`,
  27: `${VILLAGE_DATA_BASE}/27.json`,
  14: `${VILLAGE_DATA_BASE}/14.json`,
  17: `${VILLAGE_DATA_BASE}/17.json`,
  15: `${VILLAGE_DATA_BASE}/15.json`,
  13: `${VILLAGE_DATA_BASE}/13.json`,
  21: `${VILLAGE_DATA_BASE}/21.json`,
  34: `${VILLAGE_DATA_BASE}/34.json`,
  3: `${VILLAGE_DATA_BASE}/3.json`,
  8: `${VILLAGE_DATA_BASE}/8.json`,
  11: `${VILLAGE_DATA_BASE}/11.json`,
  33: `${VILLAGE_DATA_BASE}/33.json`,
  36: `${VILLAGE_DATA_BASE}/36.json`,
  38: `${VILLAGE_DATA_BASE}/38.json`,
  16: `${VILLAGE_DATA_BASE}/16.json`,
  9: `${VILLAGE_DATA_BASE}/9.json`,
  5: `${VILLAGE_DATA_BASE}/5.json`,
  19: `${VILLAGE_DATA_BASE}/19.json`,
};

export const loadVillageChunk = (
  stateCode: number
): Promise<{ VILLAGES_BY_SUBDISTRICT: Record<number, RegionPlace[]> }> => {
  const url = VILLAGE_DATA_URL[stateCode];
  if (!url) {
    return Promise.reject(
      new Error(`No village chunk for state code ${stateCode}`)
    );
  }
  return fetch(url).then((res) => {
    if (!res.ok) {
      throw new Error(
        `Village data for state code ${stateCode} unavailable (${res.status})`
      );
    }
    return res.json().then((data) => ({
      VILLAGES_BY_SUBDISTRICT: data as Record<number, RegionPlace[]>,
    }));
  });
};